In [2]:
import numpy as np
from numpy import array

NumPy is written mostly in C which is much faster
than Python

NumPy arrays are used with homogenous
(same) data types only, whereas lists (for example)
can contain any data type. This fact means
NumPy can be more efficient with its memory
usage


NumPy has the ability to divide up sub-tasks and
run them in parallel.

At first glance, a NumPy array resembles a List (or in the case
of multi-dimensional arrays, a List of Lists...)


In [3]:
list_1 = [1, 2, 3,] # A list

array_1 = array([1, 2, 3]) #1 Dimentional Array

In [4]:
print (list_1)

[1, 2, 3]


In [5]:
print (array_1)

[1 2 3]


In [6]:
list_2 = [[1, 2, 3], [4, 5, 6]] #List of Lists


#2 Dimentional Array
array_2 = array([[1, 2, 3],
 [4, 5, 6]])

In [7]:
print (list_2)
print (array_2)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


###Creating Arrays 1

Creating a 1-D array

In [8]:
array_np=np.array([1,2,3,4,5,6])

array_np


array([1, 2, 3, 4, 5, 6])

Creating a 2-D array


In [9]:
array_np_2=([[1,2,3], [4,5,6]])

array_np_2

[[1, 2, 3], [4, 5, 6]]

Creating an array filled with zeros


In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

Creating an array filled with ones


In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

###Creating Arrays 2

Creating an array of evenly spaced values (start, stop, step)

In [15]:
np.arange(2,18,4) #(start, stop, step)

array([ 2,  6, 10, 14])

Creating an array of random values (shown as 2x3 matrix)


In [16]:
np.random.random((2,3))

array([[0.7804159 , 0.93713663, 0.48527518],
       [0.83838631, 0.63858309, 0.62806667]])

Creating an array filled with given value (dimensions, value)


In [17]:
np.full(4, 10)

array([10, 10, 10, 10])

Creating an empty array (fills with arbitrary, un-initialized values)

In [18]:
np.empty(5)

array([1., 1., 1., 1., 1.])

###Creating Arrays 3

Creating an array of evenly spaced values (low, high, num-values)


In [19]:
np.linspace(1,3,5)

array([1. , 1.5, 2. , 2.5, 3. ])

Creating an array of random integers (low, high, size)


In [20]:
np.random.randint(2,7,5)

array([6, 4, 5, 5, 5])

###Summary Operations 1

In [22]:
my_1d_array = np.random.randint(0, 10, size=7)
my_1d_array

array([8, 5, 5, 7, 4, 8, 0])

In [23]:
np.random.randint(0, 10, 7)

array([1, 3, 8, 0, 8, 2, 6])

Max, Min, Mean, Sum, Standard Deviation


In [24]:
my_1d_array.max()

np.int64(8)

In [25]:
my_1d_array.min()

np.int64(0)

In [26]:
my_1d_array.mean()

np.float64(5.285714285714286)

In [27]:
my_1d_array.sum()

np.int64(37)

In [28]:
my_1d_array.std()

np.float64(2.602981022612657)

###Summary Operations 2

Example 2-Dimensional Array


In [29]:
my_2d_array = np.random.randint(0, 10, size=(2, 3))
my_2d_array

array([[6, 6, 5],
       [5, 7, 7]])

Maximum Value (of all values in array)


In [30]:
my_2d_array.max()

np.int64(7)

Maximum Value (of the values in "column")


In [32]:
my_2d_array.max(axis=0) #max in each column

array([6, 7, 7])

Maximum Value (of the values in "row")


In [33]:
my_2d_array.max(axis=1) #max in each row

array([6, 7])

###Math Operations 1

Example 1-Dimensional Array


In [35]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

Addition, Subtraction, Multiplication, Division

In [36]:
a+10

array([11, 12, 13, 14, 15])

In [37]:
a-10

array([-9, -8, -7, -6, -5])

In [38]:
a*10

array([10, 20, 30, 40, 50])

In [39]:
a/10

array([0.1, 0.2, 0.3, 0.4, 0.5])

###Math Operations 2

Example 1-Dimensional Array


In [41]:
a = np.array([-2,-1,0,1,2])
a

array([-2, -1,  0,  1,  2])

Square, Square Root, Trigonometry, Signs (Positive or Negative)

In [42]:
np.square(a)

array([4, 1, 0, 1, 4])

In [43]:
np.sqrt(a)

array([       nan,        nan, 0.        , 1.        , 1.41421356])

In [44]:
np.sin(a)

array([-0.90929743, -0.84147098,  0.        ,  0.84147098,  0.90929743])

In [45]:
np.cos(a)

array([-0.41614684,  0.54030231,  1.        ,  0.54030231, -0.41614684])

In [46]:
np.tan(a)

array([ 2.18503986, -1.55740772,  0.        ,  1.55740772, -2.18503986])

In [47]:
np.sign(a)

array([-1, -1,  0,  1,  1])

###Math Operations 3

Example: Multiple Arrays


In [48]:
a = np.array([1,2,3])
b = np.array([4,5,6])


Arithmetic on multiple arrays & dot product


In [51]:
np.add(a,b) # or a+b

array([5, 7, 9])

In [52]:
a+b

array([5, 7, 9])

In [54]:
np.subtract(a,b)

array([-3, -3, -3])

In [55]:
a-b

array([-3, -3, -3])

In [56]:
np.multiply(a,b)

array([ 4, 10, 18])

In [57]:
a*b

array([ 4, 10, 18])

In [58]:
np.divide(a,b)

array([0.25, 0.4 , 0.5 ])

In [59]:
a/b

array([0.25, 0.4 , 0.5 ])

In [50]:
np.dot(a,b) #dot product

np.int64(32)

Array Comparison

Element-wise comparison (which elements are equal)


In [60]:
a ==b

array([False, False, False])

Array comparison (are arrays equal)


In [61]:
np.array_equal(a,b)

False

###Accessing Elements 1

Example 1-Dimensional Array


In [63]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

Element at specific index


In [65]:
a[0]

np.int64(1)

In [68]:
a[1:4]

array([2, 3, 4])

In [67]:
a[-1]

np.int64(5)

###Accessing Elements 2

In [70]:
a=np.array([[1,2,3], [4,5,6]])

In [71]:
a

array([[1, 2, 3],
       [4, 5, 6]])

Element at specific index (here this returns "row" 1)


In [72]:
a[0]

array([1, 2, 3])

In [73]:
a[0][1]

np.int64(2)

###Re-shaping Arrays

Example 2-Dimensional Array


Re-shape (here to 3 rows & 2 columns)


In [74]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
a

array([[1, 2, 3],
       [4, 5, 6]])

Re-shape (here to a 1-Dimensional array)


In [76]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [77]:
a.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [78]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

###Stacking Arrays

Example: Multiple Arrays


In [80]:
a = np.array([1,2,3])
b= np.array([4,5,6])

Horizontal Stack


In [82]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

Vertical Stack

In [83]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

###Array Features

Example 2-Dimensional Array


In [84]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

Array Shape (length of each dimension)


In [87]:
a.shape

(2, 3)

Number of dimensions

In [88]:
a.ndim

2

Number of elements

In [89]:
a.size

6

##A Planetary Example!

Here we are going to calculate the volumes of the eight planets
in our solar system - based upon their radius measurements.


We are going to do this all using NumPy!


After that - we're going to crank it up! Instead of just doing this
for eight planets, we will run this for one million made-up
planets.

This will not only showcase some of the key functionality of
NumPy - but also the incredible speed at which it can run
calculations!

###Our data...


We have a NumPy array holding the radius distance for each of
the eight planets!




| Planet   | Radius (km) |
|----------|-------------|
| Mercury  | 2439.7      |
| Venus    | 6051.8      |
| Earth    | 6371        |
| Mars     | 3389.7      |
| Jupiter  | 69911       |
| Saturn   | 58232       |
| Uranus   | 25362       |
| Neptune  | 24622       |


In [90]:
radii = np.array([2439.7, 6051.8, 6371, 3389.7, 69911, 58232, 25362, 24622])

###Calculating the volumes!


Here we will create a new array called volumes and we will
apply the formula for calculating volume from radius to our
radii array!


$$
\text{volume (sphere)} = \frac{4}{3} \pi r^3
$$

In [91]:
volumes = 4/3 * np.pi*radii**3

In [92]:
volumes

array([6.08272087e+10, 9.28415346e+11, 1.08320692e+12, 1.63144486e+11,
       1.43128181e+15, 8.27129915e+14, 6.83343557e+13, 6.25257040e+13])

Because of the way NumPy works - it does this very, very quickly

It applies the volume formula to each of the values of the radii
array essentially in one go, rather than looping through them
one at a time, meaning the overall time taken is low.


Eight is easy though - let's crank it up a notch...


###Cranking it up...

Instead of the radius measurements for eight planets, we will
create an array that contains measurements for one million
made-up planets.

To do this we use the random functionality
within NumPy to ask for one million random integers, each
which will be a value between 1 and 1,000...


In [93]:
radii = np.random.randint(1, 1000, 1000000)

Since we have over-written the radii array, we can run the same
volume calculation code below...



Before you hit run - how long do you think it will take to run this
calculation for one million planets?!

In [94]:
volumes = 4/3 * np.pi * radii**3

In [95]:
volumes

array([2.34352853e+09, 6.86419732e+07, 6.93115551e+08, ...,
       8.17283234e+05, 2.57244078e+06, 2.58153067e+09])

Run! Wow, NumPy is faaast!


It processed this for one million planets, in a fraction of a
second! This is a simple example of why this can be such a
useful library for tasks in Python!